### ISSUE TITLE
promise not returned

### ISSUE THREAD

**Issue by Wirnex** [betastreet/exchange-pubsub#8]
when publish to the pubsub warnings show up in the log
```
(node:9778) Warning: a promise was created in a handler at /opt/app/node_modules/exchange-pubsub/lib/queue-pubsub.js:73:42 but was not returned from it

(node:9778) Warning: a promise was created in a handler at domain.js:314:12 but was not returned from it, see http://goo.gl/rRqMUw at new Promise (/opt/app/node_modules/bluebird/js/release/promise.js:79:10)
```

**Comment by 6utt3rfly** [comment]
PR #9
